# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da9d595a5e2def7ee879897a8f16f3e4cb9f62932d48b9444c06ce60dda44fef98bdc08771e4ab4605a29d4676ed1807632c5f1f1f51406b14f26de1ba3ccef

test:
  secret_key_base: 9e04842bb5a556708e5418f2c7e90740733a40d56ee4037bbf63975ec3ff62b43dd327aa063eb994dda802fd0845d6558653f4ea6a29eb8b3c4f49dada9ffea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
